openapi: 3.0.0
info:
  title: Vehicle Management API
  version: 1.0.0
  description: API для управления коллекцией транспортных средств с дополнительными операциями
  contact:
    name: API Support
    email: help-please@mail.ru

servers:
  - url: http://localhost:8080/api
    description: Development server

tags:
  - name: vehicles
    description: Операции с транспортными средствами
  - name: statistics
    description: Статистические операции
  - name: shop
    description: Дополнительные операции магазина

paths:
  /vehicles:
    get:
      tags: [vehicles]
      summary: Получить массив транспортных средств
      description: Возвращает массив транспортных средств с поддержкой сортировки, фильтрации и постраничного вывода
      parameters:
        - name: page
          in: query
          description: Номер страницы (начиная с 1)
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: size
          in: query
          description: Размер страницы
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: sort
          in: query
          description: Поле для сортировки (name, enginePower, numberOfWheels, capacity, fuelType)
          schema:
            type: string
        - name: order
          in: query
          description: Порядок сортировки (asc, desc)
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - name: name
          in: query
          description: Фильтр по имени (точное совпадение)
          schema:
            type: string
        - name: minEnginePower
          in: query
          description: Минимальная мощность двигателя
          schema:
            type: integer
            minimum: 1
        - name: maxEnginePower
          in: query
          description: Максимальная мощность двигателя
          schema:
            type: integer
            minimum: 1
        - name: minWheels
          in: query
          description: Минимальное количество колес
          schema:
            type: integer
            minimum: 1
        - name: maxWheels
          in: query
          description: Максимальное количество колес
          schema:
            type: integer
            minimum: 1
        - name: minCapacity
          in: query
          description: Минимальная вместимость
          schema:
            type: number
            minimum: 0
            exclusiveMinimum: true
        - name: maxCapacity
          in: query
          description: Максимальная вместимость
          schema:
            type: number
            minimum: 0
            exclusiveMinimum: true
        - name: fuelType
          in: query
          description: Тип топлива
          schema:
            type: string
            enum: [KEROSENE, ELECTRICITY, DIESEL, ALCOHOL, NUCLEAR]
      responses:
        '200':
          description: Успешное получение списка транспортных средств
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vehicle'
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer
                  currentPage:
                    type: integer
        '400':
          description: Неверные параметры запроса
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '422':
          description: Ошибка валидации параметров запроса
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

    post:
      tags: [vehicles]
      summary: Добавить новое транспортное средство
      description: Создает новое транспортное средство с автоматической генерацией ID и даты создания
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleCreate'
            examples:
              validExample:
                value:
                  name: "Tesla Model S"
                  coordinates: {x: 100, y: 200}
                  enginePower: 1020
                  numberOfWheels: 4
                  capacity: 5.0
                  fuelType: "ELECTRICITY"
      responses:
        '201':
          description: Транспортное средство успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверные данные транспортного средства
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '409':
          description: Конфликт данных (дублирование и т.д.)
        '422':
          description: Ошибка валидации данных
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /vehicles/{id}:
    get:
      tags: [vehicles]
      summary: Получить транспортное средство по ID
      description: Возвращает транспортное средство по указанному идентификатору
      parameters:
        - name: id
          in: path
          required: true
          description: ID транспортного средства
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Транспортное средство найдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверный ID
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Транспортное средство не найдено
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

    put:
      tags: [vehicles]
      summary: Обновить транспортное средство
      description: Обновляет данные транспортного средства по указанному ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID транспортного средства
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleUpdate'
            examples:
              validUpdate:
                value:
                  name: "Tesla Model S Plaid"
                  enginePower: 1100
      responses:
        '200':
          description: Транспортное средство успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверные данные для обновления
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Транспортное средство не найдено
        '409':
          description: Конфликт данных при обновлении
        '422':
          description: Ошибка валидации данных
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

    delete:
      tags: [vehicles]
      summary: Удалить транспортное средство
      description: Удаляет транспортное средство по указанному ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID транспортного средства
          schema:
            type: integer
            minimum: 1
      responses:
        '204':
          description: Транспортное средство успешно удалено
        '400':
          description: Неверный ID
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Транспортное средство не найдено
        '409':
          description: Конфликт при удалении
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /vehicles/stats/average-engine-power:
    get:
      tags: [statistics]
      summary: Средняя мощность двигателя
      description: Рассчитывает среднее значение поля enginePower для всех объектов
      responses:
        '200':
          description: Успешный расчет
          content:
            application/json:
              schema:
                type: object
                properties:
                  averageEnginePower:
                    type: number
                    format: float
                    description: Средняя мощность двигателя
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Нет данных для расчета
        '422':
          description: Невозможно вычислить среднее значение
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /vehicles/stats/count-by-wheels/{wheels}:
    get:
      tags: [statistics]
      summary: Количество объектов по количеству колес
      description: Возвращает количество объектов, значение поля numberOfWheels которых равно заданному
      parameters:
        - name: wheels
          in: path
          required: true
          description: Количество колес для поиска
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Успешный подсчет
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Количество транспортных средств
        '400':
          description: Неверное количество колес
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Нет транспортных средств с указанным количеством колес
        '422':
          description: Ошибка обработки запроса
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /vehicles/search/name-starts-with/{prefix}:
    get:
      tags: [vehicles]
      summary: Поиск по началу имени
      description: Возвращает массив объектов, значение поля name которых начинается с заданной подстроки
      parameters:
        - name: prefix
          in: path
          required: true
          description: Начальная подстрока имени
          schema:
            type: string
            minLength: 1
      responses:
        '200':
          description: Успешный поиск
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверная подстрока
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Объекты не найдены
        '422':
          description: Ошибка обработки поискового запроса
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /shop/search/by-engine-power/{from}/{to}:
    get:
      tags: [shop]
      summary: Поиск по диапазону мощности двигателя
      description: Найти все транспортные средства с мощностью двигателя в заданном диапазоне
      parameters:
        - name: from
          in: path
          required: true
          description: Минимальная мощность двигателя
          schema:
            type: integer
            minimum: 1
        - name: to
          in: path
          required: true
          description: Максимальная мощность двигателя
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Успешный поиск
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверный диапазон мощности (from > to)
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Объекты не найдены
        '422':
          description: Недопустимый диапазон значений
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

  /shop/add-wheels/{vehicle-id}/{number-of-wheels}:
    patch:
      tags: [shop]
      summary: Добавить колеса транспортному средству
      description: Добавить транспортному средству с заданным id указанное число колёс
      parameters:
        - name: vehicle-id
          in: path
          required: true
          description: ID транспортного средства
          schema:
            type: integer
            minimum: 1
        - name: number-of-wheels
          in: path
          required: true
          description: Количество колес для добавления
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Колеса успешно добавлены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
        '400':
          description: Неверные параметры (отрицательное количество колес и т.д.)
        '401':
          description: Требуется аутентификация
        '403':
          description: Доступ запрещен
        '404':
          description: Транспортное средство не найдено
        '409':
          description: Конфликт при обновлении (превышение максимального количества колес)
        '422':
          description: Невозможно добавить указанное количество колес
        '429':
          description: Слишком много запросов
        '500':
          description: Внутренняя ошибка сервера
        '503':
          description: Сервис временно недоступен

components:
  schemas:
    Vehicle:
      type: object
      required:
        - id
        - name
        - coordinates
        - creationDate
        - capacity
        - fuelType
      properties:
        id:
          type: integer
          description: Уникальный идентификатор
          minimum: 1
        name:
          type: string
          description: Наименование транспортного средства
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          description: Дата создания
        enginePower:
          type: integer
          description: Мощность двигателя
          minimum: 1
          nullable: true
        numberOfWheels:
          type: integer
          description: Количество колес
          minimum: 1
          nullable: true
        capacity:
          type: number
          format: float
          description: Вместимость
          minimum: 0
          exclusiveMinimum: true
        fuelType:
          $ref: '#/components/schemas/FuelType'

    VehicleCreate:
      type: object
      required:
        - name
        - coordinates
        - capacity
        - fuelType
      properties:
        name:
          type: string
          description: Наименование транспортного средства
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        enginePower:
          type: integer
          description: Мощность двигателя
          minimum: 1
          nullable: true
        numberOfWheels:
          type: integer
          description: Количество колес
          minimum: 1
          nullable: true
        capacity:
          type: number
          format: float
          description: Вместимость
          minimum: 0
          exclusiveMinimum: true
        fuelType:
          $ref: '#/components/schemas/FuelType'

    VehicleUpdate:
      type: object
      properties:
        name:
          type: string
          description: Наименование транспортного средства
          minLength: 1
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        enginePower:
          type: integer
          description: Мощность двигателя
          minimum: 1
          nullable: true
        numberOfWheels:
          type: integer
          description: Количество колес
          minimum: 1
          nullable: true
        capacity:
          type: number
          format: float
          description: Вместимость
          minimum: 0
          exclusiveMinimum: true
        fuelType:
          $ref: '#/components/schemas/FuelType'

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
          format: int64
          description: Координата X
        y:
          type: integer
          description: Координата Y
          nullable: false

    FuelType:
      type: string
      enum: [KEROSENE, ELECTRICITY, DIESEL, ALCOHOL, NUCLEAR]
      description: Тип топлива

  responses:
    BadRequest:
      description: Неверный запрос
    Unauthorized:
      description: Требуется аутентификация
    Forbidden:
      description: Доступ запрещен
    NotFound:
      description: Ресурс не найден
    TooManyRequests:
      description: Слишком много запросов
    ServerError:
      description: Внутренняя ошибка сервера
    ServiceUnavailable:
      description: Сервис временно недоступen

  parameters:
    PageNumber:
      name: page
      in: query
      description: Номер страницы
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSize:
      name: size
      in: query
      description: Размер страницы
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20